# Site settings
title: Izabella Lönnqvist
email: izabellaricko@gmail.com
description: Portfolio
baseurl: ""
url: "https://izlonnqvist.se"
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Izabella Lönnqvist" # Set default author name
      categories: ""
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
